#!/usr/bin/bash

clear && echo "Do you want to install the dependencies? [y][n]" 

read ans
if [[ $ans = "y" ]];
  then clear && echo "Installing..." && sleep 2s && sudo apt-get install figlet && sudo apt-get install aircrack-ng && sudo apt-get install macchanger && clear && figlet -f standard "Done!" && sleep 2s && bash



elif [[ $ans = "n" ]];
then clear && echo "Okay. Stopping the installer..." && sleep 2s && bash


else echo "Please type a valid option." && sleep 2s && bash installer
fi
